### ISSUE TITLE
You are running a development build of Vue.

### ISSUE THREAD

**Issue by djmalibiran** [viivue/acf-icomoon#15]
I am getting this message logged in my console:

```
You are running a development build of Vue.
Make sure to use the production build (*.prod.js) when deploying for production.
```

**Comment by daomapsieucap** [comment]
@phucbm Could you check this one? I think it'll improve our plugin quality to get rid of the console notices.

**Comment by daomapsieucap** [comment]
@djmalibiran The warning message was removed from the latest version we've just released. Please update the plugin.
