### ISSUE TITLE
Improve search UX

### ISSUE THREAD

**Issue by daomapsieucap** [viivue/acf-icomoon#6]
I think it would be nice if
- We have some messages for the case that no items were found after searching 👀.
- There are some loading icons 💨 when searching, so users can know that they are doing the search task.

**Comment by phucbm** [comment]
You're right about the "no item found" message, will do. 
I also thought about the loading icon but the waiting time is pretty short actually, but I agree that it does look better with the loading icon. Maybe I'll add some more delay so we will have more time to enjoy it 😆

**Comment by phucbm** [comment]
Done with ACF Icomoon v4.0
