### ISSUE TITLE
Icomoon field doesn’t work when use it in repeater field for Gutenberg editor

### ISSUE THREAD

**Issue by phucbm** [viivue/acf-icomoon#9]
Linked with [this issue](https://wordpress.org/support/topic/icomoon-field-doesnt-work-when-use-it-in-repeater-field-for-gutenberg-editor/) on WP.

---

Icomoon field don’t save in post or page, if use field in repeater mode for Guttenberg block. With like [settings](https://drive.google.com/file/d/11kWM-YlX_uvOiDTHd4U4jA_uGY61Tm1x/view?usp=sharing).

Otherwise, nice pluggin. Thanks for your work.
![frame](https://user-images.githubusercontent.com/14942380/164380389-13d74a62-afbe-4eed-9517-53d18b04e449.png)

**Comment by qurtopianodesign** [comment]
same problem, any solution?

**Comment by phucbm** [comment]
@qurtopianodesign
The issue has been solved with the latest version 4.0.2. Could you update the plugin and try again?
